version: '3.8'
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: moreehoney
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=examplepassword
      - DB_NAME=moreehoney
      - API_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db_data:
